version: "3.8"
services:
  gateway:
    build:
      context: gateway/docker
      dockerfile: development/nginx/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
  api-php-cli:
    build:
      context: api/docker
      dockerfile: development/php-cli/Dockerfile
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
    volumes:
      - ./api:/app
  api:
    build:
      context: api/docker
      dockerfile: development/nginx/Dockerfile
    volumes:
      - ./api:/app
  api-php-fpm:
    build:
      context: api/docker
      dockerfile: development/php-fpm/Dockerfile
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      PHP_IDE_CONFIG: serverName=API
    volumes:
      - ./api:/app:cached
      - ./api/var:/symfony/var
      - ./api/vendor:/symfony/vendor
  api-postgres:
    image: postgres:13.4-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "54321:5432"
  frontend:
    build:
      context: frontend/docker/development/nginx

#  frontend-node:
#    build:
#      context: frontend/docker/development/node
#    volumes:
#      - ./frontend:/app
##    command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && npm run start"
#    command: npm run start
#    tty: true
  frontend-node-cli:
    build:
      context: frontend/docker/development/node
    volumes:
      - ./frontend:/app
  cucumber-node-cli:
    build:
      context: cucumber/docker/development/node
    volumes:
      - ./cucumber:/app
